# Generated by Django 5.2.4 on 2025-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_follow_created_at_alter_follow_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulepost",
            name="schedule_time",
        ),
        migrations.AddField(
            model_name="schedulepost",
            name="schedule_time",
            field=models.TimeField(),
        ),
    ]