# Generated by Django 5.2.4 on 2025-07-24 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_schedulepost_schedule_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulepost",
            name="is_post",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="chat.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.hashtag",
            ),
        ),
    ]
